[2025-02-25T09:50:59.696+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: yfinance_ingestion_dag.store_raw_data_in_hdfs scheduled__2025-02-09T00:00:00+00:00 [queued]>
[2025-02-25T09:50:59.767+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: yfinance_ingestion_dag.store_raw_data_in_hdfs scheduled__2025-02-09T00:00:00+00:00 [queued]>
[2025-02-25T09:50:59.776+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2025-02-25T09:50:59.886+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): store_raw_data_in_hdfs> on 2025-02-09 00:00:00+00:00
[2025-02-25T09:50:59.939+0000] {standard_task_runner.py:57} INFO - Started process 1181 to run task
[2025-02-25T09:50:59.964+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'yfinance_ingestion_dag', 'store_raw_data_in_hdfs', 'scheduled__2025-02-09T00:00:00+00:00', '--job-id', '124', '--raw', '--subdir', 'DAGS_FOLDER/test_hello.py', '--cfg-path', '/tmp/tmpou5k3a28']
[2025-02-25T09:50:59.984+0000] {standard_task_runner.py:85} INFO - Job 124: Subtask store_raw_data_in_hdfs
[2025-02-25T09:51:00.436+0000] {task_command.py:415} INFO - Running <TaskInstance: yfinance_ingestion_dag.store_raw_data_in_hdfs scheduled__2025-02-09T00:00:00+00:00 [running]> on host 6dbd75e48aaa
[2025-02-25T09:51:01.025+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='etudiant' AIRFLOW_CTX_DAG_ID='yfinance_ingestion_dag' AIRFLOW_CTX_TASK_ID='store_raw_data_in_hdfs' AIRFLOW_CTX_EXECUTION_DATE='2025-02-09T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-02-09T00:00:00+00:00'
[2025-02-25T09:51:40.418+0000] {python.py:194} INFO - Done. Returned value was: None
[2025-02-25T09:51:40.491+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=yfinance_ingestion_dag, task_id=store_raw_data_in_hdfs, execution_date=20250209T000000, start_date=20250225T095059, end_date=20250225T095140
[2025-02-25T09:51:40.846+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2025-02-25T09:51:40.919+0000] {taskinstance.py:2784} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-02-26T20:45:23.573+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: yfinance_ingestion_dag.store_raw_data_in_hdfs scheduled__2025-02-09T00:00:00+00:00 [queued]>
[2025-02-26T20:45:23.591+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: yfinance_ingestion_dag.store_raw_data_in_hdfs scheduled__2025-02-09T00:00:00+00:00 [queued]>
[2025-02-26T20:45:23.592+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2025-02-26T20:45:23.616+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): store_raw_data_in_hdfs> on 2025-02-09 00:00:00+00:00
[2025-02-26T20:45:23.625+0000] {standard_task_runner.py:57} INFO - Started process 2567 to run task
[2025-02-26T20:45:23.629+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'yfinance_ingestion_dag', 'store_raw_data_in_hdfs', 'scheduled__2025-02-09T00:00:00+00:00', '--job-id', '382', '--raw', '--subdir', 'DAGS_FOLDER/pipeline.py', '--cfg-path', '/tmp/tmp67j88dxu']
[2025-02-26T20:45:23.636+0000] {standard_task_runner.py:85} INFO - Job 382: Subtask store_raw_data_in_hdfs
[2025-02-26T20:45:23.709+0000] {task_command.py:415} INFO - Running <TaskInstance: yfinance_ingestion_dag.store_raw_data_in_hdfs scheduled__2025-02-09T00:00:00+00:00 [running]> on host 3c0faf52b292
[2025-02-26T20:45:23.835+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='etudiant' AIRFLOW_CTX_DAG_ID='yfinance_ingestion_dag' AIRFLOW_CTX_TASK_ID='store_raw_data_in_hdfs' AIRFLOW_CTX_EXECUTION_DATE='2025-02-09T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-02-09T00:00:00+00:00'
[2025-02-26T20:45:30.956+0000] {python.py:194} INFO - Done. Returned value was: None
[2025-02-26T20:45:30.973+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=yfinance_ingestion_dag, task_id=store_raw_data_in_hdfs, execution_date=20250209T000000, start_date=20250226T204523, end_date=20250226T204530
[2025-02-26T20:45:31.206+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2025-02-26T20:45:31.235+0000] {taskinstance.py:2784} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-02-27T14:56:06.255+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: yfinance_ingestion_dag.store_raw_data_in_hdfs scheduled__2025-02-09T00:00:00+00:00 [queued]>
[2025-02-27T14:56:06.349+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: yfinance_ingestion_dag.store_raw_data_in_hdfs scheduled__2025-02-09T00:00:00+00:00 [queued]>
[2025-02-27T14:56:06.350+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 1
[2025-02-27T14:56:06.412+0000] {taskinstance.py:1380} INFO - Executing <Task(PythonOperator): store_raw_data_in_hdfs> on 2025-02-09 00:00:00+00:00
[2025-02-27T14:56:06.435+0000] {standard_task_runner.py:57} INFO - Started process 460 to run task
[2025-02-27T14:56:06.465+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'yfinance_ingestion_dag', 'store_raw_data_in_hdfs', 'scheduled__2025-02-09T00:00:00+00:00', '--job-id', '90', '--raw', '--subdir', 'DAGS_FOLDER/pipeline.py', '--cfg-path', '/tmp/tmpqwjo6y5b']
[2025-02-27T14:56:06.479+0000] {standard_task_runner.py:85} INFO - Job 90: Subtask store_raw_data_in_hdfs
[2025-02-27T14:56:06.780+0000] {task_command.py:415} INFO - Running <TaskInstance: yfinance_ingestion_dag.store_raw_data_in_hdfs scheduled__2025-02-09T00:00:00+00:00 [running]> on host a71f042480b6
[2025-02-27T14:56:07.105+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='etudiant' AIRFLOW_CTX_DAG_ID='yfinance_ingestion_dag' AIRFLOW_CTX_TASK_ID='store_raw_data_in_hdfs' AIRFLOW_CTX_EXECUTION_DATE='2025-02-09T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-02-09T00:00:00+00:00'
[2025-02-27T14:56:07.157+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/pipeline.py", line 82, in store_raw_data_in_hdfs
    with open(local_file, 'w') as f:
PermissionError: [Errno 13] Permission denied: '/mnt/hadoop_data/yfinance_raw.json'
[2025-02-27T14:56:07.205+0000] {taskinstance.py:1398} INFO - Marking task as FAILED. dag_id=yfinance_ingestion_dag, task_id=store_raw_data_in_hdfs, execution_date=20250209T000000, start_date=20250227T145606, end_date=20250227T145607
[2025-02-27T14:56:07.275+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 90 for task store_raw_data_in_hdfs ([Errno 13] Permission denied: '/mnt/hadoop_data/yfinance_raw.json'; 460)
[2025-02-27T14:56:07.351+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2025-02-27T14:56:07.497+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
