[2025-02-25T09:49:57.259+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: yfinance_ingestion_dag.store_raw_data_in_hdfs scheduled__2025-01-22T00:00:00+00:00 [queued]>
[2025-02-25T09:49:57.349+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: yfinance_ingestion_dag.store_raw_data_in_hdfs scheduled__2025-01-22T00:00:00+00:00 [queued]>
[2025-02-25T09:49:57.353+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2025-02-25T09:49:57.396+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): store_raw_data_in_hdfs> on 2025-01-22 00:00:00+00:00
[2025-02-25T09:49:57.414+0000] {standard_task_runner.py:57} INFO - Started process 789 to run task
[2025-02-25T09:49:57.423+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'yfinance_ingestion_dag', 'store_raw_data_in_hdfs', 'scheduled__2025-01-22T00:00:00+00:00', '--job-id', '83', '--raw', '--subdir', 'DAGS_FOLDER/test_hello.py', '--cfg-path', '/tmp/tmpwsdhwm9m']
[2025-02-25T09:49:57.448+0000] {standard_task_runner.py:85} INFO - Job 83: Subtask store_raw_data_in_hdfs
[2025-02-25T09:49:57.602+0000] {task_command.py:415} INFO - Running <TaskInstance: yfinance_ingestion_dag.store_raw_data_in_hdfs scheduled__2025-01-22T00:00:00+00:00 [running]> on host 6dbd75e48aaa
[2025-02-25T09:49:58.033+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='etudiant' AIRFLOW_CTX_DAG_ID='yfinance_ingestion_dag' AIRFLOW_CTX_TASK_ID='store_raw_data_in_hdfs' AIRFLOW_CTX_EXECUTION_DATE='2025-01-22T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-01-22T00:00:00+00:00'
[2025-02-25T09:50:40.395+0000] {python.py:194} INFO - Done. Returned value was: None
[2025-02-25T09:50:40.419+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=yfinance_ingestion_dag, task_id=store_raw_data_in_hdfs, execution_date=20250122T000000, start_date=20250225T094957, end_date=20250225T095040
[2025-02-25T09:50:40.492+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2025-02-25T09:50:40.527+0000] {taskinstance.py:2784} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-02-26T20:25:27.305+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: yfinance_ingestion_dag.store_raw_data_in_hdfs scheduled__2025-01-22T00:00:00+00:00 [queued]>
[2025-02-26T20:25:27.498+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: yfinance_ingestion_dag.store_raw_data_in_hdfs scheduled__2025-01-22T00:00:00+00:00 [queued]>
[2025-02-26T20:25:27.513+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2025-02-26T20:25:27.784+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): store_raw_data_in_hdfs> on 2025-01-22 00:00:00+00:00
[2025-02-26T20:25:27.815+0000] {standard_task_runner.py:57} INFO - Started process 1298 to run task
[2025-02-26T20:25:27.823+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'yfinance_ingestion_dag', 'store_raw_data_in_hdfs', 'scheduled__2025-01-22T00:00:00+00:00', '--job-id', '142', '--raw', '--subdir', 'DAGS_FOLDER/pipeline.py', '--cfg-path', '/tmp/tmpp5d0tbbm']
[2025-02-26T20:25:27.837+0000] {standard_task_runner.py:85} INFO - Job 142: Subtask store_raw_data_in_hdfs
[2025-02-26T20:25:28.383+0000] {task_command.py:415} INFO - Running <TaskInstance: yfinance_ingestion_dag.store_raw_data_in_hdfs scheduled__2025-01-22T00:00:00+00:00 [running]> on host c96a1011f5a3
[2025-02-26T20:25:29.310+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='etudiant' AIRFLOW_CTX_DAG_ID='yfinance_ingestion_dag' AIRFLOW_CTX_TASK_ID='store_raw_data_in_hdfs' AIRFLOW_CTX_EXECUTION_DATE='2025-01-22T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-01-22T00:00:00+00:00'
[2025-02-26T20:26:04.789+0000] {python.py:194} INFO - Done. Returned value was: None
[2025-02-26T20:26:04.812+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=yfinance_ingestion_dag, task_id=store_raw_data_in_hdfs, execution_date=20250122T000000, start_date=20250226T202527, end_date=20250226T202604
[2025-02-26T20:26:04.861+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2025-02-26T20:26:04.894+0000] {taskinstance.py:2784} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-02-26T20:39:14.559+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: yfinance_ingestion_dag.store_raw_data_in_hdfs scheduled__2025-01-22T00:00:00+00:00 [queued]>
[2025-02-26T20:39:14.644+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: yfinance_ingestion_dag.store_raw_data_in_hdfs scheduled__2025-01-22T00:00:00+00:00 [queued]>
[2025-02-26T20:39:14.656+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2025-02-26T20:39:14.765+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): store_raw_data_in_hdfs> on 2025-01-22 00:00:00+00:00
[2025-02-26T20:39:13.783+0000] {standard_task_runner.py:57} INFO - Started process 589 to run task
[2025-02-26T20:39:13.829+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'yfinance_ingestion_dag', 'store_raw_data_in_hdfs', 'scheduled__2025-01-22T00:00:00+00:00', '--job-id', '242', '--raw', '--subdir', 'DAGS_FOLDER/pipeline.py', '--cfg-path', '/tmp/tmps_9pz4k8']
[2025-02-26T20:39:13.842+0000] {standard_task_runner.py:85} INFO - Job 242: Subtask store_raw_data_in_hdfs
[2025-02-26T20:39:14.092+0000] {task_command.py:415} INFO - Running <TaskInstance: yfinance_ingestion_dag.store_raw_data_in_hdfs scheduled__2025-01-22T00:00:00+00:00 [running]> on host 3c0faf52b292
[2025-02-26T20:39:14.494+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='etudiant' AIRFLOW_CTX_DAG_ID='yfinance_ingestion_dag' AIRFLOW_CTX_TASK_ID='store_raw_data_in_hdfs' AIRFLOW_CTX_EXECUTION_DATE='2025-01-22T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-01-22T00:00:00+00:00'
[2025-02-26T20:39:15.009+0000] {python.py:194} INFO - Done. Returned value was: None
[2025-02-26T20:39:15.048+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=yfinance_ingestion_dag, task_id=store_raw_data_in_hdfs, execution_date=20250122T000000, start_date=20250226T203914, end_date=20250226T203915
[2025-02-26T20:39:15.185+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2025-02-26T20:39:15.302+0000] {taskinstance.py:2784} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-02-26T20:42:24.247+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: yfinance_ingestion_dag.store_raw_data_in_hdfs scheduled__2025-01-22T00:00:00+00:00 [queued]>
[2025-02-26T20:42:24.259+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: yfinance_ingestion_dag.store_raw_data_in_hdfs scheduled__2025-01-22T00:00:00+00:00 [queued]>
[2025-02-26T20:42:24.259+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2025-02-26T20:42:24.279+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): store_raw_data_in_hdfs> on 2025-01-22 00:00:00+00:00
[2025-02-26T20:42:24.287+0000] {standard_task_runner.py:57} INFO - Started process 1799 to run task
[2025-02-26T20:42:24.292+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'yfinance_ingestion_dag', 'store_raw_data_in_hdfs', 'scheduled__2025-01-22T00:00:00+00:00', '--job-id', '327', '--raw', '--subdir', 'DAGS_FOLDER/pipeline.py', '--cfg-path', '/tmp/tmpmfzf0r0l']
[2025-02-26T20:42:24.297+0000] {standard_task_runner.py:85} INFO - Job 327: Subtask store_raw_data_in_hdfs
[2025-02-26T20:42:24.360+0000] {task_command.py:415} INFO - Running <TaskInstance: yfinance_ingestion_dag.store_raw_data_in_hdfs scheduled__2025-01-22T00:00:00+00:00 [running]> on host 3c0faf52b292
[2025-02-26T20:42:24.471+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='etudiant' AIRFLOW_CTX_DAG_ID='yfinance_ingestion_dag' AIRFLOW_CTX_TASK_ID='store_raw_data_in_hdfs' AIRFLOW_CTX_EXECUTION_DATE='2025-01-22T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-01-22T00:00:00+00:00'
[2025-02-26T20:42:31.443+0000] {python.py:194} INFO - Done. Returned value was: None
[2025-02-26T20:42:31.462+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=yfinance_ingestion_dag, task_id=store_raw_data_in_hdfs, execution_date=20250122T000000, start_date=20250226T204224, end_date=20250226T204231
[2025-02-26T20:42:31.518+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2025-02-26T20:42:31.550+0000] {taskinstance.py:2784} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-02-27T14:55:37.331+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: yfinance_ingestion_dag.store_raw_data_in_hdfs scheduled__2025-01-22T00:00:00+00:00 [queued]>
[2025-02-27T14:55:37.410+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: yfinance_ingestion_dag.store_raw_data_in_hdfs scheduled__2025-01-22T00:00:00+00:00 [queued]>
[2025-02-27T14:55:37.412+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 1
[2025-02-27T14:55:37.566+0000] {taskinstance.py:1380} INFO - Executing <Task(PythonOperator): store_raw_data_in_hdfs> on 2025-01-22 00:00:00+00:00
[2025-02-27T14:55:37.594+0000] {standard_task_runner.py:57} INFO - Started process 354 to run task
[2025-02-27T14:55:37.618+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'yfinance_ingestion_dag', 'store_raw_data_in_hdfs', 'scheduled__2025-01-22T00:00:00+00:00', '--job-id', '56', '--raw', '--subdir', 'DAGS_FOLDER/pipeline.py', '--cfg-path', '/tmp/tmp93mnl9ia']
[2025-02-27T14:55:37.641+0000] {standard_task_runner.py:85} INFO - Job 56: Subtask store_raw_data_in_hdfs
[2025-02-27T14:55:37.949+0000] {task_command.py:415} INFO - Running <TaskInstance: yfinance_ingestion_dag.store_raw_data_in_hdfs scheduled__2025-01-22T00:00:00+00:00 [running]> on host a71f042480b6
[2025-02-27T14:55:38.473+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='etudiant' AIRFLOW_CTX_DAG_ID='yfinance_ingestion_dag' AIRFLOW_CTX_TASK_ID='store_raw_data_in_hdfs' AIRFLOW_CTX_EXECUTION_DATE='2025-01-22T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-01-22T00:00:00+00:00'
[2025-02-27T14:55:38.510+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/pipeline.py", line 82, in store_raw_data_in_hdfs
    with open(local_file, 'w') as f:
PermissionError: [Errno 13] Permission denied: '/mnt/hadoop_data/yfinance_raw.json'
[2025-02-27T14:55:38.594+0000] {taskinstance.py:1398} INFO - Marking task as FAILED. dag_id=yfinance_ingestion_dag, task_id=store_raw_data_in_hdfs, execution_date=20250122T000000, start_date=20250227T145537, end_date=20250227T145538
[2025-02-27T14:55:39.049+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 56 for task store_raw_data_in_hdfs ([Errno 13] Permission denied: '/mnt/hadoop_data/yfinance_raw.json'; 354)
[2025-02-27T14:55:39.102+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2025-02-27T14:55:39.170+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
