[2025-02-26T20:24:21.127+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: yfinance_ingestion_dag.run_mapreduce manual__2025-02-26T20:10:39.616487+00:00 [queued]>
[2025-02-26T20:24:21.173+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: yfinance_ingestion_dag.run_mapreduce manual__2025-02-26T20:10:39.616487+00:00 [queued]>
[2025-02-26T20:24:21.179+0000] {taskinstance.py:1361} INFO - Starting attempt 2 of 2
[2025-02-26T20:24:21.355+0000] {taskinstance.py:1382} INFO - Executing <Task(BashOperator): run_mapreduce> on 2025-02-26 20:10:39.616487+00:00
[2025-02-26T20:24:21.371+0000] {standard_task_runner.py:57} INFO - Started process 1030 to run task
[2025-02-26T20:24:21.468+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'yfinance_ingestion_dag', 'run_mapreduce', 'manual__2025-02-26T20:10:39.616487+00:00', '--job-id', '112', '--raw', '--subdir', 'DAGS_FOLDER/pipeline.py', '--cfg-path', '/tmp/tmps18_dw51']
[2025-02-26T20:24:21.491+0000] {standard_task_runner.py:85} INFO - Job 112: Subtask run_mapreduce
[2025-02-26T20:24:22.009+0000] {task_command.py:415} INFO - Running <TaskInstance: yfinance_ingestion_dag.run_mapreduce manual__2025-02-26T20:10:39.616487+00:00 [running]> on host c96a1011f5a3
[2025-02-26T20:24:22.711+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='etudiant' AIRFLOW_CTX_DAG_ID='yfinance_ingestion_dag' AIRFLOW_CTX_TASK_ID='run_mapreduce' AIRFLOW_CTX_EXECUTION_DATE='2025-02-26T20:10:39.616487+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-02-26T20:10:39.616487+00:00'
[2025-02-26T20:24:22.721+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-02-26T20:24:22.741+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', '\n        docker exec -i -u root namenode bash -c \'         cd /tmp &&         cp /mnt/hadoop_data/mapreduce/mapper.py . &&         cp /mnt/hadoop_data/mapreduce/reducer.py . &&         chmod +x mapper.py reducer.py &&         hdfs dfs -rm -r hdfs:///user/etudiant/crypto/processed/YYYY=2025/MM=02/DD=26 || true &&         hadoop jar /opt/hadoop-3.2.1/share/hadoop/tools/lib/hadoop-streaming-3.2.1.jar         -files mapper.py,reducer.py         -mapper "python mapper.py"         -reducer "python reducer.py"         -input hdfs:///user/etudiant/crypto/raw/YYYY=2025/MM=02/DD=26/yfinance_raw.json         -output hdfs:///user/etudiant/crypto/processed/YYYY=2025/MM=02/DD=26\'\n        ']
[2025-02-26T20:24:22.841+0000] {subprocess.py:86} INFO - Output:
[2025-02-26T20:24:38.093+0000] {subprocess.py:93} INFO - rm: `hdfs:///user/etudiant/crypto/processed/YYYY=2025/MM=02/DD=26': No such file or directory
[2025-02-26T20:24:52.701+0000] {subprocess.py:93} INFO - 2025-02-26 20:24:52,682 INFO impl.MetricsConfig: Loaded properties from hadoop-metrics2.properties
[2025-02-26T20:24:53.135+0000] {subprocess.py:93} INFO - 2025-02-26 20:24:53,132 INFO impl.MetricsSystemImpl: Scheduled Metric snapshot period at 10 second(s).
[2025-02-26T20:24:53.136+0000] {subprocess.py:93} INFO - 2025-02-26 20:24:53,133 INFO impl.MetricsSystemImpl: JobTracker metrics system started
[2025-02-26T20:24:53.336+0000] {subprocess.py:93} INFO - 2025-02-26 20:24:53,334 WARN impl.MetricsSystemImpl: JobTracker metrics system already initialized!
[2025-02-26T20:24:55.321+0000] {subprocess.py:93} INFO - 2025-02-26 20:24:55,319 INFO mapred.FileInputFormat: Total input files to process : 1
[2025-02-26T20:24:54.609+0000] {subprocess.py:93} INFO - 2025-02-26 20:24:54,606 INFO mapreduce.JobSubmitter: number of splits:1
[2025-02-26T20:24:55.765+0000] {subprocess.py:93} INFO - 2025-02-26 20:24:55,758 INFO mapreduce.JobSubmitter: Submitting tokens for job: job_local1431633520_0001
[2025-02-26T20:24:55.770+0000] {subprocess.py:93} INFO - 2025-02-26 20:24:55,758 INFO mapreduce.JobSubmitter: Executing with tokens: []
[2025-02-26T20:24:56.227+0000] {subprocess.py:93} INFO - 2025-02-26 20:24:56,224 INFO mapred.LocalDistributedCacheManager: Localized file:/tmp/mapper.py as file:/tmp/hadoop-root/mapred/local/job_local1431633520_0001_7dfdce57-7980-4954-ab6e-3d7050c28bd2/mapper.py
[2025-02-26T20:24:56.254+0000] {subprocess.py:93} INFO - 2025-02-26 20:24:56,252 INFO mapred.LocalDistributedCacheManager: Localized file:/tmp/reducer.py as file:/tmp/hadoop-root/mapred/local/job_local1431633520_0001_a842ba2f-be42-4391-b607-44f5966895c5/reducer.py
[2025-02-26T20:24:56.332+0000] {subprocess.py:93} INFO - 2025-02-26 20:24:56,329 INFO mapreduce.Job: The url to track the job: http://localhost:8080/
[2025-02-26T20:24:56.334+0000] {subprocess.py:93} INFO - 2025-02-26 20:24:56,332 INFO mapreduce.Job: Running job: job_local1431633520_0001
[2025-02-26T20:24:56.338+0000] {subprocess.py:93} INFO - 2025-02-26 20:24:56,335 INFO mapred.LocalJobRunner: OutputCommitter set in config null
[2025-02-26T20:24:56.346+0000] {subprocess.py:93} INFO - 2025-02-26 20:24:56,339 INFO mapred.LocalJobRunner: OutputCommitter is org.apache.hadoop.mapred.FileOutputCommitter
[2025-02-26T20:24:56.354+0000] {subprocess.py:93} INFO - 2025-02-26 20:24:56,352 INFO output.FileOutputCommitter: File Output Committer Algorithm version is 2
[2025-02-26T20:24:56.355+0000] {subprocess.py:93} INFO - 2025-02-26 20:24:56,352 INFO output.FileOutputCommitter: FileOutputCommitter skip cleanup _temporary folders under output directory:false, ignore cleanup failures: false
[2025-02-26T20:24:56.426+0000] {subprocess.py:93} INFO - 2025-02-26 20:24:56,424 INFO mapred.LocalJobRunner: Waiting for map tasks
[2025-02-26T20:24:56.435+0000] {subprocess.py:93} INFO - 2025-02-26 20:24:56,431 INFO mapred.LocalJobRunner: Starting task: attempt_local1431633520_0001_m_000000_0
[2025-02-26T20:24:56.476+0000] {subprocess.py:93} INFO - 2025-02-26 20:24:56,474 INFO output.FileOutputCommitter: File Output Committer Algorithm version is 2
[2025-02-26T20:24:56.477+0000] {subprocess.py:93} INFO - 2025-02-26 20:24:56,474 INFO output.FileOutputCommitter: FileOutputCommitter skip cleanup _temporary folders under output directory:false, ignore cleanup failures: false
[2025-02-26T20:24:56.537+0000] {subprocess.py:93} INFO - 2025-02-26 20:24:56,529 INFO mapred.Task:  Using ResourceCalculatorProcessTree : [ ]
[2025-02-26T20:24:56.586+0000] {subprocess.py:93} INFO - 2025-02-26 20:24:56,578 INFO mapred.MapTask: Processing split: hdfs://namenode:9000/user/etudiant/crypto/raw/YYYY=2025/MM=02/DD=26/yfinance_raw.json:0+19763
[2025-02-26T20:24:56.664+0000] {subprocess.py:93} INFO - 2025-02-26 20:24:56,657 INFO mapred.MapTask: numReduceTasks: 1
[2025-02-26T20:24:56.791+0000] {subprocess.py:93} INFO - 2025-02-26 20:24:56,789 INFO mapred.MapTask: (EQUATOR) 0 kvi 26214396(104857584)
[2025-02-26T20:24:56.792+0000] {subprocess.py:93} INFO - 2025-02-26 20:24:56,789 INFO mapred.MapTask: mapreduce.task.io.sort.mb: 100
[2025-02-26T20:24:56.793+0000] {subprocess.py:93} INFO - 2025-02-26 20:24:56,789 INFO mapred.MapTask: soft limit at 83886080
[2025-02-26T20:24:56.794+0000] {subprocess.py:93} INFO - 2025-02-26 20:24:56,789 INFO mapred.MapTask: bufstart = 0; bufvoid = 104857600
[2025-02-26T20:24:56.794+0000] {subprocess.py:93} INFO - 2025-02-26 20:24:56,789 INFO mapred.MapTask: kvstart = 26214396; length = 6553600
[2025-02-26T20:24:56.801+0000] {subprocess.py:93} INFO - 2025-02-26 20:24:56,795 INFO mapred.MapTask: Map output collector class = org.apache.hadoop.mapred.MapTask$MapOutputBuffer
[2025-02-26T20:24:56.819+0000] {subprocess.py:93} INFO - 2025-02-26 20:24:56,816 INFO streaming.PipeMapRed: PipeMapRed exec [/usr/bin/python, mapper.py]
[2025-02-26T20:24:56.826+0000] {subprocess.py:93} INFO - 2025-02-26 20:24:56,824 INFO Configuration.deprecation: mapred.work.output.dir is deprecated. Instead, use mapreduce.task.output.dir
[2025-02-26T20:24:56.828+0000] {subprocess.py:93} INFO - 2025-02-26 20:24:56,825 INFO Configuration.deprecation: map.input.start is deprecated. Instead, use mapreduce.map.input.start
[2025-02-26T20:24:56.828+0000] {subprocess.py:93} INFO - 2025-02-26 20:24:56,826 INFO Configuration.deprecation: mapred.task.is.map is deprecated. Instead, use mapreduce.task.ismap
[2025-02-26T20:24:56.829+0000] {subprocess.py:93} INFO - 2025-02-26 20:24:56,827 INFO Configuration.deprecation: mapred.task.id is deprecated. Instead, use mapreduce.task.attempt.id
[2025-02-26T20:24:56.830+0000] {subprocess.py:93} INFO - 2025-02-26 20:24:56,828 INFO Configuration.deprecation: mapred.tip.id is deprecated. Instead, use mapreduce.task.id
[2025-02-26T20:24:56.831+0000] {subprocess.py:93} INFO - 2025-02-26 20:24:56,828 INFO Configuration.deprecation: mapred.local.dir is deprecated. Instead, use mapreduce.cluster.local.dir
[2025-02-26T20:24:56.859+0000] {subprocess.py:93} INFO - 2025-02-26 20:24:56,831 INFO Configuration.deprecation: map.input.file is deprecated. Instead, use mapreduce.map.input.file
[2025-02-26T20:24:56.860+0000] {subprocess.py:93} INFO - 2025-02-26 20:24:56,831 INFO Configuration.deprecation: mapred.skip.on is deprecated. Instead, use mapreduce.job.skiprecords
[2025-02-26T20:24:56.870+0000] {subprocess.py:93} INFO - 2025-02-26 20:24:56,832 INFO Configuration.deprecation: map.input.length is deprecated. Instead, use mapreduce.map.input.length
[2025-02-26T20:24:56.870+0000] {subprocess.py:93} INFO - 2025-02-26 20:24:56,833 INFO Configuration.deprecation: mapred.job.id is deprecated. Instead, use mapreduce.job.id
[2025-02-26T20:24:56.871+0000] {subprocess.py:93} INFO - 2025-02-26 20:24:56,833 INFO Configuration.deprecation: user.name is deprecated. Instead, use mapreduce.job.user.name
[2025-02-26T20:24:56.872+0000] {subprocess.py:93} INFO - 2025-02-26 20:24:56,834 INFO Configuration.deprecation: mapred.task.partition is deprecated. Instead, use mapreduce.task.partition
[2025-02-26T20:24:56.926+0000] {subprocess.py:93} INFO - 2025-02-26 20:24:56,922 INFO sasl.SaslDataTransferClient: SASL encryption trust check: localHostTrusted = false, remoteHostTrusted = false
[2025-02-26T20:24:56.945+0000] {subprocess.py:93} INFO -   File "mapper.py", line 27
[2025-02-26T20:24:56.946+0000] {subprocess.py:93} INFO -     print(f"{coin}\t{json.dumps(metrics)}")
[2025-02-26T20:24:56.947+0000] {subprocess.py:93} INFO -                                          ^
[2025-02-26T20:24:56.947+0000] {subprocess.py:93} INFO - SyntaxError: invalid syntax
[2025-02-26T20:24:56.951+0000] {subprocess.py:93} INFO - 2025-02-26 20:24:56,949 INFO streaming.PipeMapRed: MRErrorThread done
[2025-02-26T20:24:57.059+0000] {subprocess.py:93} INFO - 2025-02-26 20:24:57,056 INFO streaming.PipeMapRed: R/W/S=1/0/0 in:NA [rec/s] out:NA [rec/s]
[2025-02-26T20:24:57.060+0000] {subprocess.py:93} INFO - 2025-02-26 20:24:57,056 INFO streaming.PipeMapRed: R/W/S=10/0/0 in:NA [rec/s] out:NA [rec/s]
[2025-02-26T20:24:57.061+0000] {subprocess.py:93} INFO - 2025-02-26 20:24:57,058 INFO streaming.PipeMapRed: R/W/S=100/0/0 in:NA [rec/s] out:NA [rec/s]
[2025-02-26T20:24:57.080+0000] {subprocess.py:93} INFO - 2025-02-26 20:24:57,074 WARN streaming.PipeMapRed: {}
[2025-02-26T20:24:57.081+0000] {subprocess.py:93} INFO - java.io.IOException: Stream closed
[2025-02-26T20:24:57.081+0000] {subprocess.py:93} INFO - 	at java.lang.ProcessBuilder$NullOutputStream.write(ProcessBuilder.java:433)
[2025-02-26T20:24:57.082+0000] {subprocess.py:93} INFO - 	at java.io.OutputStream.write(OutputStream.java:116)
[2025-02-26T20:24:57.083+0000] {subprocess.py:93} INFO - 	at java.io.BufferedOutputStream.write(BufferedOutputStream.java:122)
[2025-02-26T20:24:57.084+0000] {subprocess.py:93} INFO - 	at java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:82)
[2025-02-26T20:24:57.084+0000] {subprocess.py:93} INFO - 	at java.io.BufferedOutputStream.flush(BufferedOutputStream.java:140)
[2025-02-26T20:24:57.086+0000] {subprocess.py:93} INFO - 	at java.io.DataOutputStream.flush(DataOutputStream.java:123)
[2025-02-26T20:24:57.086+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.streaming.PipeMapRed.mapRedFinished(PipeMapRed.java:532)
[2025-02-26T20:24:57.087+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.streaming.PipeMapper.close(PipeMapper.java:130)
[2025-02-26T20:24:57.089+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.mapred.MapRunner.run(MapRunner.java:61)
[2025-02-26T20:24:57.090+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.streaming.PipeMapRunner.run(PipeMapRunner.java:34)
[2025-02-26T20:24:57.090+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.mapred.MapTask.runOldMapper(MapTask.java:465)
[2025-02-26T20:24:57.091+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.mapred.MapTask.run(MapTask.java:349)
[2025-02-26T20:24:57.093+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.mapred.LocalJobRunner$Job$MapTaskRunnable.run(LocalJobRunner.java:271)
[2025-02-26T20:24:57.094+0000] {subprocess.py:93} INFO - 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[2025-02-26T20:24:57.095+0000] {subprocess.py:93} INFO - 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[2025-02-26T20:24:57.096+0000] {subprocess.py:93} INFO - 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[2025-02-26T20:24:57.096+0000] {subprocess.py:93} INFO - 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[2025-02-26T20:24:57.097+0000] {subprocess.py:93} INFO - 	at java.lang.Thread.run(Thread.java:748)
[2025-02-26T20:24:57.097+0000] {subprocess.py:93} INFO - 2025-02-26 20:24:57,078 INFO streaming.PipeMapRed: PipeMapRed failed!
[2025-02-26T20:24:57.098+0000] {subprocess.py:93} INFO - java.lang.RuntimeException: PipeMapRed.waitOutputThreads(): subprocess failed with code 1
[2025-02-26T20:24:57.099+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.streaming.PipeMapRed.waitOutputThreads(PipeMapRed.java:326)
[2025-02-26T20:24:57.099+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.streaming.PipeMapRed.mapRedFinished(PipeMapRed.java:539)
[2025-02-26T20:24:57.100+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.streaming.PipeMapper.close(PipeMapper.java:130)
[2025-02-26T20:24:57.100+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.mapred.MapRunner.run(MapRunner.java:61)
[2025-02-26T20:24:57.101+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.streaming.PipeMapRunner.run(PipeMapRunner.java:34)
[2025-02-26T20:24:57.101+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.mapred.MapTask.runOldMapper(MapTask.java:465)
[2025-02-26T20:24:57.102+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.mapred.MapTask.run(MapTask.java:349)
[2025-02-26T20:24:57.103+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.mapred.LocalJobRunner$Job$MapTaskRunnable.run(LocalJobRunner.java:271)
[2025-02-26T20:24:57.104+0000] {subprocess.py:93} INFO - 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[2025-02-26T20:24:57.105+0000] {subprocess.py:93} INFO - 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[2025-02-26T20:24:57.107+0000] {subprocess.py:93} INFO - 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[2025-02-26T20:24:57.108+0000] {subprocess.py:93} INFO - 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[2025-02-26T20:24:57.109+0000] {subprocess.py:93} INFO - 	at java.lang.Thread.run(Thread.java:748)
[2025-02-26T20:24:57.110+0000] {subprocess.py:93} INFO - 2025-02-26 20:24:57,082 INFO mapred.LocalJobRunner: map task executor complete.
[2025-02-26T20:24:57.110+0000] {subprocess.py:93} INFO - 2025-02-26 20:24:57,097 WARN mapred.LocalJobRunner: job_local1431633520_0001
[2025-02-26T20:24:57.112+0000] {subprocess.py:93} INFO - java.lang.Exception: java.lang.RuntimeException: PipeMapRed.waitOutputThreads(): subprocess failed with code 1
[2025-02-26T20:24:57.112+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.mapred.LocalJobRunner$Job.runTasks(LocalJobRunner.java:492)
[2025-02-26T20:24:57.113+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.mapred.LocalJobRunner$Job.run(LocalJobRunner.java:552)
[2025-02-26T20:24:57.113+0000] {subprocess.py:93} INFO - Caused by: java.lang.RuntimeException: PipeMapRed.waitOutputThreads(): subprocess failed with code 1
[2025-02-26T20:24:57.114+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.streaming.PipeMapRed.waitOutputThreads(PipeMapRed.java:326)
[2025-02-26T20:24:57.115+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.streaming.PipeMapRed.mapRedFinished(PipeMapRed.java:539)
[2025-02-26T20:24:57.115+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.streaming.PipeMapper.close(PipeMapper.java:130)
[2025-02-26T20:24:57.116+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.mapred.MapRunner.run(MapRunner.java:61)
[2025-02-26T20:24:57.117+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.streaming.PipeMapRunner.run(PipeMapRunner.java:34)
[2025-02-26T20:24:57.117+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.mapred.MapTask.runOldMapper(MapTask.java:465)
[2025-02-26T20:24:57.118+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.mapred.MapTask.run(MapTask.java:349)
[2025-02-26T20:24:57.118+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.mapred.LocalJobRunner$Job$MapTaskRunnable.run(LocalJobRunner.java:271)
[2025-02-26T20:24:57.119+0000] {subprocess.py:93} INFO - 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[2025-02-26T20:24:57.119+0000] {subprocess.py:93} INFO - 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[2025-02-26T20:24:57.120+0000] {subprocess.py:93} INFO - 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[2025-02-26T20:24:57.120+0000] {subprocess.py:93} INFO - 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[2025-02-26T20:24:57.121+0000] {subprocess.py:93} INFO - 	at java.lang.Thread.run(Thread.java:748)
[2025-02-26T20:24:57.351+0000] {subprocess.py:93} INFO - 2025-02-26 20:24:57,349 INFO mapreduce.Job: Job job_local1431633520_0001 running in uber mode : false
[2025-02-26T20:24:57.352+0000] {subprocess.py:93} INFO - 2025-02-26 20:24:57,351 INFO mapreduce.Job:  map 0% reduce 0%
[2025-02-26T20:24:57.356+0000] {subprocess.py:93} INFO - 2025-02-26 20:24:57,355 INFO mapreduce.Job: Job job_local1431633520_0001 failed with state FAILED due to: NA
[2025-02-26T20:24:57.373+0000] {subprocess.py:93} INFO - 2025-02-26 20:24:57,371 INFO mapreduce.Job: Counters: 0
[2025-02-26T20:24:57.374+0000] {subprocess.py:93} INFO - 2025-02-26 20:24:57,371 ERROR streaming.StreamJob: Job not successful!
[2025-02-26T20:24:57.375+0000] {subprocess.py:93} INFO - Streaming Command Failed!
[2025-02-26T20:24:57.863+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2025-02-26T20:24:57.879+0000] {taskinstance.py:1943} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-02-26T20:24:57.885+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=yfinance_ingestion_dag, task_id=run_mapreduce, execution_date=20250226T201039, start_date=20250226T202421, end_date=20250226T202457
[2025-02-26T20:24:57.904+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 112 for task run_mapreduce (Bash command failed. The command returned a non-zero exit code 1.; 1030)
[2025-02-26T20:24:57.931+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2025-02-26T20:24:57.953+0000] {taskinstance.py:2784} INFO - 0 downstream tasks scheduled from follow-on schedule check
