[2025-02-26T19:30:21.841+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: yfinance_ingestion_and_process_dag.run_mapreduce scheduled__2025-01-18T00:00:00+00:00 [queued]>
[2025-02-26T19:30:21.959+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: yfinance_ingestion_and_process_dag.run_mapreduce scheduled__2025-01-18T00:00:00+00:00 [queued]>
[2025-02-26T19:30:22.012+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2025-02-26T19:30:22.246+0000] {taskinstance.py:1382} INFO - Executing <Task(BashOperator): run_mapreduce> on 2025-01-18 00:00:00+00:00
[2025-02-26T19:30:22.316+0000] {standard_task_runner.py:57} INFO - Started process 663 to run task
[2025-02-26T19:30:22.326+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'yfinance_ingestion_and_process_dag', 'run_mapreduce', 'scheduled__2025-01-18T00:00:00+00:00', '--job-id', '334', '--raw', '--subdir', 'DAGS_FOLDER/pipeline.py', '--cfg-path', '/tmp/tmpyzb1fw0b']
[2025-02-26T19:30:22.356+0000] {standard_task_runner.py:85} INFO - Job 334: Subtask run_mapreduce
[2025-02-26T19:30:22.904+0000] {task_command.py:415} INFO - Running <TaskInstance: yfinance_ingestion_and_process_dag.run_mapreduce scheduled__2025-01-18T00:00:00+00:00 [running]> on host fc9f30cfdaf1
[2025-02-26T19:30:23.798+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='etudiant' AIRFLOW_CTX_DAG_ID='yfinance_ingestion_and_process_dag' AIRFLOW_CTX_TASK_ID='run_mapreduce' AIRFLOW_CTX_EXECUTION_DATE='2025-01-18T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-01-18T00:00:00+00:00'
[2025-02-26T19:30:23.809+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-02-26T19:30:23.831+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', '\n        docker exec -i -u root namenode bash -c \'         cd /tmp &&         cp /mnt/hadoop_data/mapreduce/mapper.py . &&         cp /mnt/hadoop_data/mapreduce/reducer.py . &&         chmod +x mapper.py reducer.py &&         hdfs dfs -rm -r hdfs:///user/etudiant/crypto/processed/YYYY=2025/MM=01/DD=18 || true &&         hadoop jar /opt/hadoop-3.2.1/share/hadoop/tools/lib/hadoop-streaming-3.2.1.jar         -files mapper.py,reducer.py         -mapper "python mapper.py"         -reducer "python reducer.py"         -input hdfs:///user/etudiant/crypto/raw/YYYY=2025/MM=01/DD=18/yfinance_raw.json         -output hdfs:///user/etudiant/crypto/processed/YYYY=2025/MM=01/DD=18\'\n        ']
[2025-02-26T19:30:23.920+0000] {subprocess.py:86} INFO - Output:
[2025-02-26T19:30:44.178+0000] {subprocess.py:93} INFO - rm: `hdfs:///user/etudiant/crypto/processed/YYYY=2025/MM=01/DD=18': No such file or directory
[2025-02-26T19:31:04.271+0000] {subprocess.py:93} INFO - 2025-02-26 19:31:04,231 INFO impl.MetricsConfig: Loaded properties from hadoop-metrics2.properties
[2025-02-26T19:31:05.592+0000] {subprocess.py:93} INFO - 2025-02-26 19:31:05,589 INFO impl.MetricsSystemImpl: Scheduled Metric snapshot period at 10 second(s).
[2025-02-26T19:31:05.600+0000] {subprocess.py:93} INFO - 2025-02-26 19:31:05,589 INFO impl.MetricsSystemImpl: JobTracker metrics system started
[2025-02-26T19:31:06.100+0000] {subprocess.py:93} INFO - 2025-02-26 19:31:06,088 WARN impl.MetricsSystemImpl: JobTracker metrics system already initialized!
[2025-02-26T19:31:10.529+0000] {subprocess.py:93} INFO - 2025-02-26 19:31:10,448 INFO mapred.FileInputFormat: Total input files to process : 1
[2025-02-26T19:31:10.041+0000] {subprocess.py:93} INFO - 2025-02-26 19:31:09,972 INFO mapreduce.JobSubmitter: number of splits:1
[2025-02-26T19:31:12.785+0000] {subprocess.py:93} INFO - 2025-02-26 19:31:12,767 INFO mapreduce.JobSubmitter: Submitting tokens for job: job_local2147041628_0001
[2025-02-26T19:31:12.802+0000] {subprocess.py:93} INFO - 2025-02-26 19:31:12,767 INFO mapreduce.JobSubmitter: Executing with tokens: []
[2025-02-26T19:31:18.780+0000] {subprocess.py:93} INFO - 2025-02-26 19:31:18,765 INFO mapred.LocalDistributedCacheManager: Localized file:/tmp/mapper.py as file:/tmp/hadoop-root/mapred/local/job_local2147041628_0001_d222d12a-d594-453f-9403-b3761a3d5900/mapper.py
[2025-02-26T19:31:19.563+0000] {subprocess.py:93} INFO - 2025-02-26 19:31:19,543 INFO mapred.LocalDistributedCacheManager: Localized file:/tmp/reducer.py as file:/tmp/hadoop-root/mapred/local/job_local2147041628_0001_5b4b36a9-b70d-4687-83d5-923decd5bc5c/reducer.py
[2025-02-26T19:31:21.611+0000] {subprocess.py:93} INFO - 2025-02-26 19:31:21,608 INFO mapreduce.Job: The url to track the job: http://localhost:8080/
[2025-02-26T19:31:21.657+0000] {subprocess.py:93} INFO - 2025-02-26 19:31:21,641 INFO mapreduce.Job: Running job: job_local2147041628_0001
[2025-02-26T19:31:21.777+0000] {subprocess.py:93} INFO - 2025-02-26 19:31:21,766 INFO mapred.LocalJobRunner: OutputCommitter set in config null
[2025-02-26T19:31:21.816+0000] {subprocess.py:93} INFO - 2025-02-26 19:31:21,806 INFO mapred.LocalJobRunner: OutputCommitter is org.apache.hadoop.mapred.FileOutputCommitter
[2025-02-26T19:31:21.911+0000] {subprocess.py:93} INFO - 2025-02-26 19:31:21,902 INFO output.FileOutputCommitter: File Output Committer Algorithm version is 2
[2025-02-26T19:31:21.917+0000] {subprocess.py:93} INFO - 2025-02-26 19:31:21,902 INFO output.FileOutputCommitter: FileOutputCommitter skip cleanup _temporary folders under output directory:false, ignore cleanup failures: false
[2025-02-26T19:31:22.734+0000] {subprocess.py:93} INFO - 2025-02-26 19:31:22,711 INFO mapreduce.Job: Job job_local2147041628_0001 running in uber mode : false
[2025-02-26T19:31:22.735+0000] {subprocess.py:93} INFO - 2025-02-26 19:31:22,713 INFO mapreduce.Job:  map 0% reduce 0%
[2025-02-26T19:31:23.201+0000] {subprocess.py:93} INFO - 2025-02-26 19:31:23,183 INFO mapred.LocalJobRunner: Waiting for map tasks
[2025-02-26T19:31:23.269+0000] {subprocess.py:93} INFO - 2025-02-26 19:31:23,258 INFO mapred.LocalJobRunner: Starting task: attempt_local2147041628_0001_m_000000_0
[2025-02-26T19:31:24.125+0000] {subprocess.py:93} INFO - 2025-02-26 19:31:24,095 INFO output.FileOutputCommitter: File Output Committer Algorithm version is 2
[2025-02-26T19:31:24.142+0000] {subprocess.py:93} INFO - 2025-02-26 19:31:24,102 INFO output.FileOutputCommitter: FileOutputCommitter skip cleanup _temporary folders under output directory:false, ignore cleanup failures: false
[2025-02-26T19:31:25.427+0000] {subprocess.py:93} INFO - 2025-02-26 19:31:25,417 INFO mapred.Task:  Using ResourceCalculatorProcessTree : [ ]
[2025-02-26T19:31:25.893+0000] {subprocess.py:93} INFO - 2025-02-26 19:31:25,890 INFO mapred.MapTask: Processing split: hdfs://namenode:9000/user/etudiant/crypto/raw/YYYY=2025/MM=01/DD=18/yfinance_raw.json:0+23882
[2025-02-26T19:31:26.298+0000] {subprocess.py:93} INFO - 2025-02-26 19:31:26,293 INFO mapred.MapTask: numReduceTasks: 1
[2025-02-26T19:31:26.683+0000] {subprocess.py:93} INFO - 2025-02-26 19:31:26,667 INFO mapred.MapTask: (EQUATOR) 0 kvi 26214396(104857584)
[2025-02-26T19:31:26.684+0000] {subprocess.py:93} INFO - 2025-02-26 19:31:26,667 INFO mapred.MapTask: mapreduce.task.io.sort.mb: 100
[2025-02-26T19:31:26.685+0000] {subprocess.py:93} INFO - 2025-02-26 19:31:26,667 INFO mapred.MapTask: soft limit at 83886080
[2025-02-26T19:31:26.686+0000] {subprocess.py:93} INFO - 2025-02-26 19:31:26,667 INFO mapred.MapTask: bufstart = 0; bufvoid = 104857600
[2025-02-26T19:31:26.686+0000] {subprocess.py:93} INFO - 2025-02-26 19:31:26,667 INFO mapred.MapTask: kvstart = 26214396; length = 6553600
[2025-02-26T19:31:26.741+0000] {subprocess.py:93} INFO - 2025-02-26 19:31:26,730 INFO mapred.MapTask: Map output collector class = org.apache.hadoop.mapred.MapTask$MapOutputBuffer
[2025-02-26T19:31:26.913+0000] {subprocess.py:93} INFO - 2025-02-26 19:31:26,870 INFO streaming.PipeMapRed: PipeMapRed exec [/usr/bin/python, mapper.py]
[2025-02-26T19:31:26.914+0000] {subprocess.py:93} INFO - 2025-02-26 19:31:26,898 INFO Configuration.deprecation: mapred.work.output.dir is deprecated. Instead, use mapreduce.task.output.dir
[2025-02-26T19:31:26.916+0000] {subprocess.py:93} INFO - 2025-02-26 19:31:26,899 INFO Configuration.deprecation: map.input.start is deprecated. Instead, use mapreduce.map.input.start
[2025-02-26T19:31:26.918+0000] {subprocess.py:93} INFO - 2025-02-26 19:31:26,901 INFO Configuration.deprecation: mapred.task.is.map is deprecated. Instead, use mapreduce.task.ismap
[2025-02-26T19:31:26.920+0000] {subprocess.py:93} INFO - 2025-02-26 19:31:26,901 INFO Configuration.deprecation: mapred.task.id is deprecated. Instead, use mapreduce.task.attempt.id
[2025-02-26T19:31:26.933+0000] {subprocess.py:93} INFO - 2025-02-26 19:31:26,904 INFO Configuration.deprecation: mapred.tip.id is deprecated. Instead, use mapreduce.task.id
[2025-02-26T19:31:26.940+0000] {subprocess.py:93} INFO - 2025-02-26 19:31:26,905 INFO Configuration.deprecation: mapred.local.dir is deprecated. Instead, use mapreduce.cluster.local.dir
[2025-02-26T19:31:26.943+0000] {subprocess.py:93} INFO - 2025-02-26 19:31:26,910 INFO Configuration.deprecation: map.input.file is deprecated. Instead, use mapreduce.map.input.file
[2025-02-26T19:31:26.948+0000] {subprocess.py:93} INFO - 2025-02-26 19:31:26,935 INFO Configuration.deprecation: mapred.skip.on is deprecated. Instead, use mapreduce.job.skiprecords
[2025-02-26T19:31:26.968+0000] {subprocess.py:93} INFO - 2025-02-26 19:31:26,935 INFO Configuration.deprecation: map.input.length is deprecated. Instead, use mapreduce.map.input.length
[2025-02-26T19:31:27.029+0000] {subprocess.py:93} INFO - 2025-02-26 19:31:26,988 INFO Configuration.deprecation: mapred.job.id is deprecated. Instead, use mapreduce.job.id
[2025-02-26T19:31:27.031+0000] {subprocess.py:93} INFO - 2025-02-26 19:31:26,988 INFO Configuration.deprecation: user.name is deprecated. Instead, use mapreduce.job.user.name
[2025-02-26T19:31:27.031+0000] {subprocess.py:93} INFO - 2025-02-26 19:31:26,989 INFO Configuration.deprecation: mapred.task.partition is deprecated. Instead, use mapreduce.task.partition
[2025-02-26T19:31:27.483+0000] {subprocess.py:93} INFO -   File "mapper.py", line 27
[2025-02-26T19:31:27.507+0000] {subprocess.py:93} INFO -     print(f"{coin}\t{json.dumps(metrics)}")
[2025-02-26T19:31:27.526+0000] {subprocess.py:93} INFO -                                          ^
[2025-02-26T19:31:27.531+0000] {subprocess.py:93} INFO - SyntaxError: invalid syntax
[2025-02-26T19:31:27.536+0000] {subprocess.py:93} INFO - 2025-02-26 19:31:27,523 INFO streaming.PipeMapRed: MRErrorThread done
[2025-02-26T19:31:27.700+0000] {subprocess.py:93} INFO - 2025-02-26 19:31:27,693 INFO sasl.SaslDataTransferClient: SASL encryption trust check: localHostTrusted = false, remoteHostTrusted = false
[2025-02-26T19:31:29.784+0000] {subprocess.py:93} INFO - 2025-02-26 19:31:29,767 INFO streaming.PipeMapRed: R/W/S=1/0/0 in:0=1/2 [rec/s] out:0=0/2 [rec/s]
[2025-02-26T19:31:29.788+0000] {subprocess.py:93} INFO - 2025-02-26 19:31:29,778 INFO streaming.PipeMapRed: R/W/S=10/0/0 in:5=10/2 [rec/s] out:0=0/2 [rec/s]
[2025-02-26T19:31:29.793+0000] {subprocess.py:93} INFO - 2025-02-26 19:31:29,784 INFO streaming.PipeMapRed: R/W/S=100/0/0 in:50=100/2 [rec/s] out:0=0/2 [rec/s]
[2025-02-26T19:31:29.970+0000] {subprocess.py:93} INFO - 2025-02-26 19:31:29,897 WARN streaming.PipeMapRed: {}
[2025-02-26T19:31:29.977+0000] {subprocess.py:93} INFO - java.io.IOException: Stream closed
[2025-02-26T19:31:29.991+0000] {subprocess.py:93} INFO - 	at java.lang.ProcessBuilder$NullOutputStream.write(ProcessBuilder.java:433)
[2025-02-26T19:31:30.005+0000] {subprocess.py:93} INFO - 	at java.io.OutputStream.write(OutputStream.java:116)
[2025-02-26T19:31:30.010+0000] {subprocess.py:93} INFO - 	at java.io.BufferedOutputStream.write(BufferedOutputStream.java:122)
[2025-02-26T19:31:30.024+0000] {subprocess.py:93} INFO - 	at java.io.BufferedOutputStream.flushBuffer(BufferedOutputStream.java:82)
[2025-02-26T19:31:30.026+0000] {subprocess.py:93} INFO - 	at java.io.BufferedOutputStream.flush(BufferedOutputStream.java:140)
[2025-02-26T19:31:30.037+0000] {subprocess.py:93} INFO - 	at java.io.DataOutputStream.flush(DataOutputStream.java:123)
[2025-02-26T19:31:30.051+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.streaming.PipeMapRed.mapRedFinished(PipeMapRed.java:532)
[2025-02-26T19:31:30.054+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.streaming.PipeMapper.close(PipeMapper.java:130)
[2025-02-26T19:31:30.066+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.mapred.MapRunner.run(MapRunner.java:61)
[2025-02-26T19:31:30.074+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.streaming.PipeMapRunner.run(PipeMapRunner.java:34)
[2025-02-26T19:31:30.085+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.mapred.MapTask.runOldMapper(MapTask.java:465)
[2025-02-26T19:31:30.087+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.mapred.MapTask.run(MapTask.java:349)
[2025-02-26T19:31:30.089+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.mapred.LocalJobRunner$Job$MapTaskRunnable.run(LocalJobRunner.java:271)
[2025-02-26T19:31:30.091+0000] {subprocess.py:93} INFO - 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[2025-02-26T19:31:30.111+0000] {subprocess.py:93} INFO - 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[2025-02-26T19:31:30.112+0000] {subprocess.py:93} INFO - 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[2025-02-26T19:31:30.115+0000] {subprocess.py:93} INFO - 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[2025-02-26T19:31:30.127+0000] {subprocess.py:93} INFO - 	at java.lang.Thread.run(Thread.java:748)
[2025-02-26T19:31:30.129+0000] {subprocess.py:93} INFO - 2025-02-26 19:31:29,957 INFO streaming.PipeMapRed: PipeMapRed failed!
[2025-02-26T19:31:30.129+0000] {subprocess.py:93} INFO - java.lang.RuntimeException: PipeMapRed.waitOutputThreads(): subprocess failed with code 1
[2025-02-26T19:31:30.131+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.streaming.PipeMapRed.waitOutputThreads(PipeMapRed.java:326)
[2025-02-26T19:31:30.131+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.streaming.PipeMapRed.mapRedFinished(PipeMapRed.java:539)
[2025-02-26T19:31:30.132+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.streaming.PipeMapper.close(PipeMapper.java:130)
[2025-02-26T19:31:30.133+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.mapred.MapRunner.run(MapRunner.java:61)
[2025-02-26T19:31:30.135+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.streaming.PipeMapRunner.run(PipeMapRunner.java:34)
[2025-02-26T19:31:30.136+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.mapred.MapTask.runOldMapper(MapTask.java:465)
[2025-02-26T19:31:30.137+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.mapred.MapTask.run(MapTask.java:349)
[2025-02-26T19:31:30.137+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.mapred.LocalJobRunner$Job$MapTaskRunnable.run(LocalJobRunner.java:271)
[2025-02-26T19:31:30.141+0000] {subprocess.py:93} INFO - 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[2025-02-26T19:31:30.146+0000] {subprocess.py:93} INFO - 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[2025-02-26T19:31:30.147+0000] {subprocess.py:93} INFO - 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[2025-02-26T19:31:30.149+0000] {subprocess.py:93} INFO - 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[2025-02-26T19:31:30.152+0000] {subprocess.py:93} INFO - 	at java.lang.Thread.run(Thread.java:748)
[2025-02-26T19:31:30.156+0000] {subprocess.py:93} INFO - 2025-02-26 19:31:30,034 INFO mapred.LocalJobRunner: map task executor complete.
[2025-02-26T19:31:30.158+0000] {subprocess.py:93} INFO - 2025-02-26 19:31:30,143 WARN mapred.LocalJobRunner: job_local2147041628_0001
[2025-02-26T19:31:30.160+0000] {subprocess.py:93} INFO - java.lang.Exception: java.lang.RuntimeException: PipeMapRed.waitOutputThreads(): subprocess failed with code 1
[2025-02-26T19:31:30.165+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.mapred.LocalJobRunner$Job.runTasks(LocalJobRunner.java:492)
[2025-02-26T19:31:30.170+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.mapred.LocalJobRunner$Job.run(LocalJobRunner.java:552)
[2025-02-26T19:31:30.171+0000] {subprocess.py:93} INFO - Caused by: java.lang.RuntimeException: PipeMapRed.waitOutputThreads(): subprocess failed with code 1
[2025-02-26T19:31:30.172+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.streaming.PipeMapRed.waitOutputThreads(PipeMapRed.java:326)
[2025-02-26T19:31:30.176+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.streaming.PipeMapRed.mapRedFinished(PipeMapRed.java:539)
[2025-02-26T19:31:30.177+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.streaming.PipeMapper.close(PipeMapper.java:130)
[2025-02-26T19:31:30.178+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.mapred.MapRunner.run(MapRunner.java:61)
[2025-02-26T19:31:30.179+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.streaming.PipeMapRunner.run(PipeMapRunner.java:34)
[2025-02-26T19:31:30.180+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.mapred.MapTask.runOldMapper(MapTask.java:465)
[2025-02-26T19:31:30.180+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.mapred.MapTask.run(MapTask.java:349)
[2025-02-26T19:31:30.184+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.mapred.LocalJobRunner$Job$MapTaskRunnable.run(LocalJobRunner.java:271)
[2025-02-26T19:31:30.192+0000] {subprocess.py:93} INFO - 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
[2025-02-26T19:31:30.193+0000] {subprocess.py:93} INFO - 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
[2025-02-26T19:31:30.194+0000] {subprocess.py:93} INFO - 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
[2025-02-26T19:31:30.200+0000] {subprocess.py:93} INFO - 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
[2025-02-26T19:31:30.207+0000] {subprocess.py:93} INFO - 	at java.lang.Thread.run(Thread.java:748)
[2025-02-26T19:31:30.966+0000] {subprocess.py:93} INFO - 2025-02-26 19:31:30,907 INFO mapreduce.Job: Job job_local2147041628_0001 failed with state FAILED due to: NA
[2025-02-26T19:31:31.191+0000] {subprocess.py:93} INFO - 2025-02-26 19:31:31,121 INFO mapreduce.Job: Counters: 0
[2025-02-26T19:31:31.199+0000] {subprocess.py:93} INFO - 2025-02-26 19:31:31,121 ERROR streaming.StreamJob: Job not successful!
[2025-02-26T19:31:31.209+0000] {subprocess.py:93} INFO - Streaming Command Failed!
[2025-02-26T19:31:32.686+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2025-02-26T19:31:32.896+0000] {taskinstance.py:1943} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-02-26T19:31:32.958+0000] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=yfinance_ingestion_and_process_dag, task_id=run_mapreduce, execution_date=20250118T000000, start_date=20250226T193021, end_date=20250226T193132
[2025-02-26T19:31:33.753+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 334 for task run_mapreduce (Bash command failed. The command returned a non-zero exit code 1.; 663)
[2025-02-26T19:31:33.991+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2025-02-26T19:31:34.514+0000] {taskinstance.py:2784} INFO - 0 downstream tasks scheduled from follow-on schedule check
