[2025-02-26T15:19:58.009+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: coingecko_mapreduce_dag.run_mapreduce_job scheduled__2025-02-25T00:00:00+00:00 [queued]>
[2025-02-26T15:19:58.028+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: coingecko_mapreduce_dag.run_mapreduce_job scheduled__2025-02-25T00:00:00+00:00 [queued]>
[2025-02-26T15:19:58.029+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2025-02-26T15:19:58.057+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): run_mapreduce_job> on 2025-02-25 00:00:00+00:00
[2025-02-26T15:19:58.071+0000] {standard_task_runner.py:57} INFO - Started process 179 to run task
[2025-02-26T15:19:58.078+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'coingecko_mapreduce_dag', 'run_mapreduce_job', 'scheduled__2025-02-25T00:00:00+00:00', '--job-id', '208', '--raw', '--subdir', 'DAGS_FOLDER/test_hello.py', '--cfg-path', '/tmp/tmp38v1sof4']
[2025-02-26T15:19:58.083+0000] {standard_task_runner.py:85} INFO - Job 208: Subtask run_mapreduce_job
[2025-02-26T15:19:58.195+0000] {task_command.py:415} INFO - Running <TaskInstance: coingecko_mapreduce_dag.run_mapreduce_job scheduled__2025-02-25T00:00:00+00:00 [running]> on host 5b727de8dfe1
[2025-02-26T15:19:58.365+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='etudiant' AIRFLOW_CTX_DAG_ID='coingecko_mapreduce_dag' AIRFLOW_CTX_TASK_ID='run_mapreduce_job' AIRFLOW_CTX_EXECUTION_DATE='2025-02-25T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-02-25T00:00:00+00:00'
[2025-02-26T15:19:58.371+0000] {logging_mixin.py:151} INFO - Vérification de l'existence du fichier d'entrée : /user/etudiant/crypto/raw/YYYY=2025/MM=02/DD=25/coingecko_raw.json
[2025-02-26T15:20:04.404+0000] {logging_mixin.py:151} INFO - Suppression de l'ancien répertoire de sortie : /user/etudiant/crypto/output/YYYY=2025/MM=02/DD=25
[2025-02-26T15:20:09.179+0000] {logging_mixin.py:151} INFO - Avertissement : Échec de la suppression de /user/etudiant/crypto/output/YYYY=2025/MM=02/DD=25: rm: `/user/etudiant/crypto/output/YYYY=2025/MM=02/DD=25': No such file or directory
[2025-02-26T15:20:09.181+0000] {logging_mixin.py:151} INFO - Copie des scripts mapper.py et reducer.py dans HDFS.
[2025-02-26T15:20:24.176+0000] {logging_mixin.py:151} INFO - Exécution de la commande MapReduce : docker exec -i -u root namenode hadoop jar /opt/hadoop-3.2.1/share/hadoop/tools/lib/hadoop-streaming-3.2.1.jar -input /user/etudiant/crypto/raw/YYYY=2025/MM=02/DD=25/coingecko_raw.json -output /user/etudiant/crypto/output/YYYY=2025/MM=02/DD=25 -mapper python3 mapper.py -reducer python3 reducer.py -file /user/etudiant/crypto/scripts/mapper.py -file /user/etudiant/crypto/scripts/reducer.py
[2025-02-26T15:20:24.876+0000] {logging_mixin.py:151} INFO - Sortie de la commande : 
[2025-02-26T15:20:24.878+0000] {logging_mixin.py:151} INFO - Erreur lors de l'exécution de MapReduce : 2025-02-26 15:20:24,167 WARN streaming.StreamJob: -file option is deprecated, please use generic option -files instead.
File: file:/user/etudiant/crypto/scripts/mapper.py does not exist.
Try -help for more information
Streaming Command Failed!
[2025-02-26T15:20:24.880+0000] {taskinstance.py:1943} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/test_hello.py", line 88, in run_mapreduce_job
    raise subprocess.CalledProcessError(result.returncode, command, output=result.stdout, stderr=result.stderr)
subprocess.CalledProcessError: Command '['docker', 'exec', '-i', '-u', 'root', 'namenode', 'hadoop', 'jar', '/opt/hadoop-3.2.1/share/hadoop/tools/lib/hadoop-streaming-3.2.1.jar', '-input', '/user/etudiant/crypto/raw/YYYY=2025/MM=02/DD=25/coingecko_raw.json', '-output', '/user/etudiant/crypto/output/YYYY=2025/MM=02/DD=25', '-mapper', 'python3 mapper.py', '-reducer', 'python3 reducer.py', '-file', '/user/etudiant/crypto/scripts/mapper.py', '-file', '/user/etudiant/crypto/scripts/reducer.py']' returned non-zero exit status 1.
[2025-02-26T15:20:24.907+0000] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=coingecko_mapreduce_dag, task_id=run_mapreduce_job, execution_date=20250225T000000, start_date=20250226T151958, end_date=20250226T152024
[2025-02-26T15:20:25.020+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 208 for task run_mapreduce_job (Command '['docker', 'exec', '-i', '-u', 'root', 'namenode', 'hadoop', 'jar', '/opt/hadoop-3.2.1/share/hadoop/tools/lib/hadoop-streaming-3.2.1.jar', '-input', '/user/etudiant/crypto/raw/YYYY=2025/MM=02/DD=25/coingecko_raw.json', '-output', '/user/etudiant/crypto/output/YYYY=2025/MM=02/DD=25', '-mapper', 'python3 mapper.py', '-reducer', 'python3 reducer.py', '-file', '/user/etudiant/crypto/scripts/mapper.py', '-file', '/user/etudiant/crypto/scripts/reducer.py']' returned non-zero exit status 1.; 179)
[2025-02-26T15:20:25.076+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2025-02-26T15:20:25.126+0000] {taskinstance.py:2784} INFO - 0 downstream tasks scheduled from follow-on schedule check
